import localFont from "next/font/local";
import "./globals.css";

const funnel = localFont({
  src: "../public/fonts/Funnel.ttf",
  display: "swap",
  variable: "--font-funnel",
});

const gothic = localFont({
  src: "../public/fonts/Gothic.ttf",
  display: "swap",
  variable: "--font-gothic",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${funnel.variable} ${gothic.variable}`} suppressHydrationWarning>
      <body className={` antialiased overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
